#!/usr/bin/env bash
set -euo pipefail

# =============================================================================
# Post Fiat Validator Monitor — Setup
# =============================================================================
#
# Usage:
#   ./setup.sh local            All-in-one on the validator host
#   ./setup.sh split-validator  Exporters only (run on validator host)
#   ./setup.sh split-monitor    Prometheus/Grafana/Alertmanager (run on separate host)
#
# =============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

info()  { echo -e "${CYAN}[INFO]${NC} $*"; }
ok()    { echo -e "${GREEN}[OK]${NC} $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
err()   { echo -e "${RED}[ERROR]${NC} $*" >&2; }

prompt() {
    local var="$1" prompt_text="$2" default="$3"
    read -rp "$(echo -e "${CYAN}$prompt_text${NC} [${default}]: ")" val
    eval "$var='${val:-$default}'"
}

# ── Check dependencies ───────────────────────────────────────────
check_deps() {
    local missing=()
    command -v docker >/dev/null 2>&1 || missing+=("docker")
    docker compose version >/dev/null 2>&1 || missing+=("docker-compose-plugin")
    if [[ ${#missing[@]} -gt 0 ]]; then
        err "Missing: ${missing[*]}"
        err "Install Docker: https://docs.docker.com/engine/install/"
        exit 1
    fi
    ok "Docker and Compose found"
}

# ── Generate .env ────────────────────────────────────────────────
gen_env_local() {
    info "Configuring local (all-in-one) mode..."
    echo ""

    prompt RPC_URL      "postfiatd JSON-RPC URL"    "http://host.docker.internal:5005"
    prompt CONFIG_DIR   "postfiatd config directory" "/opt/postfiatd"
    prompt GRAFANA_PW   "Grafana admin password"     "postfiat"
    prompt DISCORD_URL  "Discord webhook URL (blank to skip)" ""

    cat > .env << EOF
# Generated by setup.sh — $(date -u +"%Y-%m-%d %H:%M UTC")
POSTFIATD_RPC_URL=${RPC_URL}
POSTFIATD_CONFIG_DIR=${CONFIG_DIR}
GRAFANA_PORT=3000
GRAFANA_USER=admin
GRAFANA_PASSWORD=${GRAFANA_PW}
PROMETHEUS_PORT=9090
PROMETHEUS_RETENTION=30d
ALERTMANAGER_PORT=9093
EOF
    ok "Generated .env"

    # In local mode, Prometheus is in the same Docker network as exporters
    # so we use container service names, not IPs
    sed -e 's/VALIDATOR_HOST_IP:9750/postfiatd-exporter:9750/g' \
        -e 's/VALIDATOR_HOST_IP:9100/node-exporter:9100/g' \
        -e 's/VALIDATOR_HOST_IP:8080/cadvisor:8080/g' \
        prometheus/prometheus.template.yml > prometheus/prometheus.yml
    ok "Prometheus configured for local Docker network"

    # Set Discord webhook if provided
    if [[ -n "$DISCORD_URL" ]]; then
        setup_discord "$DISCORD_URL"
    else
        warn "No Discord webhook — alerts will log but not notify"
    fi
}

gen_env_exporters() {
    info "Configuring exporters (validator host in split mode)..."
    echo ""

    prompt RPC_URL    "postfiatd JSON-RPC URL"     "http://host.docker.internal:5005"
    prompt CONFIG_DIR "postfiatd config directory"  "/opt/postfiatd"
    prompt BIND_ADDR  "Exporter bind address"       "0.0.0.0"

    cat > .env << EOF
# Generated by setup.sh — $(date -u +"%Y-%m-%d %H:%M UTC")
POSTFIATD_RPC_URL=${RPC_URL}
POSTFIATD_CONFIG_DIR=${CONFIG_DIR}
EXPORTER_BIND=${BIND_ADDR}
EOF
    ok "Generated .env"
    echo ""
    warn "Exporters will listen on ports 9750, 9100, 8080"
    warn "Make sure the monitor host can reach this machine on those ports"
    info "Firewall example: ufw allow from <monitor-ip> to any port 9750,9100,8080 proto tcp"
}

gen_env_monitor() {
    info "Configuring monitor host (Prometheus/Grafana/Alertmanager)..."
    echo ""

    prompt VALIDATOR_IP "Validator host IP (where exporters run)" ""
    prompt GRAFANA_PW   "Grafana admin password"                  "postfiat"
    prompt DISCORD_URL  "Discord webhook URL (blank to skip)"     ""

    if [[ -z "$VALIDATOR_IP" ]]; then
        err "Validator IP is required — this is where Prometheus scrapes metrics from"
        exit 1
    fi

    cat > .env << EOF
# Generated by setup.sh — $(date -u +"%Y-%m-%d %H:%M UTC")
VALIDATOR_HOST=${VALIDATOR_IP}
GRAFANA_PORT=3000
GRAFANA_USER=admin
GRAFANA_PASSWORD=${GRAFANA_PW}
PROMETHEUS_PORT=9090
PROMETHEUS_RETENTION=30d
ALERTMANAGER_PORT=9093
EOF
    ok "Generated .env"

    # Set Prometheus to scrape remote validator
    sed "s/VALIDATOR_HOST_IP/${VALIDATOR_IP}/g" \
        prometheus/prometheus.template.yml > prometheus/prometheus.yml
    ok "Prometheus configured to scrape ${VALIDATOR_IP}"

    if [[ -n "$DISCORD_URL" ]]; then
        setup_discord "$DISCORD_URL"
    else
        warn "No Discord webhook — alerts will log but not notify"
    fi
}

# ── Discord webhook setup ────────────────────────────────────────
setup_discord() {
    local url="$1"
    # Append /slack if not already there
    if [[ "$url" != */slack ]]; then
        url="${url}/slack"
        info "Appended /slack for Alertmanager compatibility"
    fi
    sed -i "s|https://discord.com/api/webhooks/YOUR_WEBHOOK_ID/YOUR_WEBHOOK_TOKEN/slack|${url}|g" \
        alertmanager/alertmanager.yml
    ok "Discord webhook configured in alertmanager.yml"
}

# ── Launch ───────────────────────────────────────────────────────
launch() {
    local compose_file="$1"
    echo ""
    info "Starting services..."
    docker compose -f "$compose_file" up -d --build
    echo ""
    ok "Stack is running!"
}

show_status_local() {
    echo ""
    echo -e "${GREEN}════════════════════════════════════════════${NC}"
    echo -e "${GREEN} Post Fiat Monitor — Local Mode${NC}"
    echo -e "${GREEN}════════════════════════════════════════════${NC}"
    echo ""
    echo -e "  Grafana:      ${CYAN}http://localhost:3000${NC}  (admin / ${GRAFANA_PW:-postfiat})"
    echo -e "  Prometheus:   ${CYAN}http://localhost:9090/targets${NC}"
    echo -e "  Alertmanager: ${CYAN}http://localhost:9093${NC}"
    echo ""
}

show_status_exporters() {
    echo ""
    echo -e "${GREEN}════════════════════════════════════════════${NC}"
    echo -e "${GREEN} Post Fiat Monitor — Validator Exporters${NC}"
    echo -e "${GREEN}════════════════════════════════════════════${NC}"
    echo ""
    echo -e "  postfiatd exporter: ${CYAN}http://0.0.0.0:9750/metrics${NC}"
    echo -e "  node exporter:      ${CYAN}http://0.0.0.0:9100/metrics${NC}"
    echo -e "  cAdvisor:           ${CYAN}http://0.0.0.0:8080/metrics${NC}"
    echo ""
    echo -e "  Now run ${YELLOW}./setup.sh split-monitor${NC} on your monitor host."
    echo ""
}

show_status_monitor() {
    echo ""
    echo -e "${GREEN}════════════════════════════════════════════${NC}"
    echo -e "${GREEN} Post Fiat Monitor — Monitor Host${NC}"
    echo -e "${GREEN}════════════════════════════════════════════${NC}"
    echo ""
    echo -e "  Grafana:      ${CYAN}http://localhost:3000${NC}  (admin / ${GRAFANA_PW:-postfiat})"
    echo -e "  Prometheus:   ${CYAN}http://localhost:9090/targets${NC}"
    echo -e "  Alertmanager: ${CYAN}http://localhost:9093${NC}"
    echo ""
    echo -e "  Scraping validator at: ${YELLOW}${VALIDATOR_IP}${NC}"
    echo ""
}

# ── Usage ────────────────────────────────────────────────────────
usage() {
    echo ""
    echo "Usage: ./setup.sh <mode>"
    echo ""
    echo "Modes:"
    echo "  local            All-in-one on the validator host (simple, less resilient)"
    echo "  split-validator  Exporters only — run this on the validator host"
    echo "  split-monitor    Prometheus/Grafana/Alertmanager — run this on a separate host"
    echo ""
    echo "Recommended: split mode with monitor on a separate Proxmox LXC or Oracle VPS"
    echo "  so alerts still fire when the validator goes down."
    echo ""
    exit 1
}

# ── Main ─────────────────────────────────────────────────────────
main() {
    local mode="${1:-}"

    echo ""
    echo -e "${CYAN}╔══════════════════════════════════════════╗${NC}"
    echo -e "${CYAN}║   Post Fiat Validator Monitor — Setup   ║${NC}"
    echo -e "${CYAN}╚══════════════════════════════════════════╝${NC}"
    echo ""

    [[ -z "$mode" ]] && usage

    check_deps

    case "$mode" in
        local)
            gen_env_local
            launch docker-compose.local.yml
            show_status_local
            ;;
        split-validator)
            gen_env_exporters
            launch docker-compose.exporters.yml
            show_status_exporters
            ;;
        split-monitor)
            gen_env_monitor
            launch docker-compose.monitor.yml
            show_status_monitor
            ;;
        *)
            usage
            ;;
    esac
}

main "$@"
